# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: ''
    weight: 10
  - name: Research
    url: 'research/'
    weight: 50
  - name: Teaching
    url: 'teaching/'
    weight: 60
  - name: CV
    url: 'cv/CV KM Fullerton Rico.pdf'